# First Window
<FirstWindow>:
    name: "first"
    MDBoxLayout:
        orientation: 'vertical'
        size_hint: .9, .9
        pos_hint: {'center_x': .5, 'center_y': .5}
        AndroidCamera:
            fit_mode: 'contain'
            play: True
        MDLabel:
            halign: 'center'
            id: category
            text: 'No Face Detected'
            font_name: 'assets/fonts/Lexend-Light.ttf'

